// Generated by ChatGPT
const templates = [
  "A {product_type} for {group} that {function}",
  "A {product_type} to {function} for {group}",
  "A {function} {product_type} for {group}",
  "A {product_type} to {function} with {group}",
  "A {group} {product_type} that {function}",
  "A {product_type} for {group} to {function}",
  "A {group} {function} {product_type}",
  "A {product_type} that {function} for {group}",
  "{function} {group} with a new {product_type}",
  "A {group} {product_type} for {function}",
];

function pickRandom(list) {
  return list[Math.floor(Math.random()*list.length)];
}

export function generateSolution() {
  const substitutions = {
    product_type: pickRandom(product_types),
    group: pickRandom(groups),
    function: '{function}',
  };
  // Performance here could be improved
  // ...but this will be invoked on a device in response to user action
  // ...in other words, I can't think of a practical reason to optimize this
  let out = pickRandom(templates);
  for (const [key, val] of Object.entries(substitutions)) {
    out = out.replace(`{${key}}`, val);
  }
  return out;
}

// Generated by ChatGPT
const product_types = [
  "app",
  "service",
  "device",
  "platform",
  "program",
  "system",
  "tool",
  "gadget",
  "invention",
  // "creation",  Doesn't actually work well
];

// An edited list from https://en.wikipedia.org/wiki/List_of_common_household_pests
const pests = [
  "mice",
  "possums",
  "rats",
  "ants",
  "bed bugs",
  "beetles",
  "cockroaches",
  "dust mites",
  "earwigs",
  "crickets",
  "flies",
  "mosquitoes",
  "moths",
  "spiders",
  "termites",
];

// An edited list from https://en.wikipedia.org/wiki/List_of_animal_sounds
const bySound = [
  "alligators",
  "alpacas",
  "antelopes",
  "badgers",
  "bats",
  "bears",
  "bees",
  "tigers",
  "lions",
  "jaguars",
  "leopards",
  "capybaras",
  "cats",
  "cattle",
  "chickens",
  "chinchillas",
  "crabs",
  "crows",
  "dogs",
  "dolphins",
  "donkeys",
  "ducks",
  "eagles",
  "elephants",
  "ferrets",
  "foxes",
  "frogs",
  "giraffes",
  "goats",
  "geese",
  "hamsters",
  "hornets",
  "horses",
  "hyenas",
  "jackals",
  "koalas",
  "leopards",
  "monkeys",
  "owls",
  "birds",
  "pigs",
  "pigeons",
  "rabbits",
  "raccoons",
  "squirrels",
  "whales",
];

// There are WAY TOO MANY legendary creatures,
// most of which the audience would be unfamiliar with,
// so here's the manual list:
const manualList = [
  "aliens",
  "dragons",
  "superheroes",
  "mutants",
  "zombies",
  "raptors",
  "dinosaurs",
  "mammoths",
  "narwhals",
  "turtles",
  "penguins",
  "lawyers",
  "beasts",
  "hunters",
  // Here, I started browsing Wikipedia's lists of occupations.
  // Most don't seem likely to be funny.
  "doctors",
  "tailors",
  "mechanics",
  "influencers",
  "janitors",
  "biologists",
  "botanists",
  "physicians",
  "astronauts",
  "astronomers",
  "astrologists",
  "cosplayers",
  "bakers",
  "musicians",
  "cartoonists",
  "authors",
  "writers",
  "wizards",
  "historians",
  "philosophers",
  "theologians",
  "soldiers",
  "generals",
  "combat medics",
  "butchers",
  "robots",
  "sonographers",
  "neurosurgeons",
];

// From https://en.wikipedia.org/wiki/List_of_sports

const athletes = [
  "breakdancers",
  "cheerleaders",
  "figure skaters",
  "freerunners",
  "gymnasts",
  "paragliders",
  "archers",
  "skateboarders",
  "scooters",  // it's not the athlete, but it's fun
  "cyclists",
  "bicycles",
  "wrestlers",
  "anglers",
  "golfers",
  "joggers",
  "sailors",
  "skiers",
  "bikers",
  "beatboxers",
];

const groups = pests.concat(bySound, manualList, athletes);